import 'package:calendario_familiar/core/models/shift_template.dart';

/// Plantillas de turnos locales predefinidas
/// Estas plantillas se sincronizan automáticamente con Firebase
final List<ShiftTemplate> localShiftTemplates = [
  ShiftTemplate(
    id: 'local-d1',
    name: 'D1',
    abbreviation: 'D1',
    colorHex: '#FF5722',
    textColorHex: '#FFFFFF',
    textSize: 16.0,
    startTime: '08:00',
    endTime: '16:00',
    description: 'Turno de día 1',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ShiftTemplate(
    id: 'local-d2',
    name: 'D2',
    abbreviation: 'D2',
    colorHex: '#4CAF50',
    textColorHex: '#FFFFFF',
    textSize: 16.0,
    startTime: '16:00',
    endTime: '00:00',
    description: 'Turno de día 2',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ShiftTemplate(
    id: 'local-n1',
    name: 'N1',
    abbreviation: 'N1',
    colorHex: '#9C27B0',
    textColorHex: '#FFFFFF',
    textSize: 16.0,
    startTime: '00:00',
    endTime: '08:00',
    description: 'Turno de noche 1',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ShiftTemplate(
    id: 'local-libre',
    name: 'Libre',
    abbreviation: 'Lib',
    colorHex: '#607D8B',
    textColorHex: '#FFFFFF',
    textSize: 16.0,
    startTime: '00:00',
    endTime: '00:00',
    description: 'Día libre',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ShiftTemplate(
    id: 'local-tarde',
    name: 'Tarde',
    abbreviation: 'T',
    colorHex: '#FF9800',
    textColorHex: '#FFFFFF',
    textSize: 16.0,
    startTime: '14:00',
    endTime: '22:00',
    description: 'Turno de tarde',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ShiftTemplate(
    id: 'local-manana',
    name: 'Mañana',
    abbreviation: 'M',
    colorHex: '#2196F3',
    textColorHex: '#FFFFFF',
    textSize: 16.0,
    startTime: '06:00',
    endTime: '14:00',
    description: 'Turno de mañana',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
];

